### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by coco66688** [Bowlingtoolkit/Xenon-Bot-JavaScript-Edition#16]
(node:38560) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
type: Value must be one of (0, 2, 4, 6).
    at C:\Users\user\Downloads\Xenon-Bot-JavaScript-Edition-master\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\user\Downloads\Xenon-Bot-JavaScript-Edition-master\Xenon-Bot-JavaScript-Edition-master\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:38560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:38560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sam920829** [comment]
@KAMUI966

**Comment by WantedYled4173** [comment]
> (node:38560) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
> type: Value must be one of (0, 2, 4, 6).
> at C:\Users\user\Downloads\Xenon-Bot-JavaScript-Edition-master\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
> at C:\Users\user\Downloads\Xenon-Bot-JavaScript-Edition-master\Xenon-Bot-JavaScript-Edition-master\node_modules\snekfetch\src\index.js:215:21
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use node --trace-warnings ... to show where the warning was created)
> (node:38560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:38560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It say "Value must be one of (0, 2, 4, 6)", so... make the values: **0, 2, 4, 6.**

**Comment by coco66688** [comment]
??????????

**Comment by WantedYled4173** [comment]
> ??????????

Value must be one of (0, 2, 4, 6).
