### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by ryuryu10** [Bowlingtoolkit/Xenon-Bot-JavaScript-Edition#4]
Found 7 files to load!

Loading command: 'backup'
Loading command: 'help'
Loading command: 'info'
Loading command: 'invite'
Loading command: 'leave'
Loading command: 'ping'
Loading command: 'tiers'
Done loading commands!
Ready !
(node:11772) UnhandledPromiseRejectionWarning: TypeError: RichEmbed is not a constructor
    at module.exports.run (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\Commands\help.js:13:29)
    at Client.<anonymous> (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\index.js:26:13)
    at Client.emit (events.js:223:5)
    at MessageCreateAction.handle (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\PC\Downloads\Xenon-Bot-JavaScript-Edition-master (1)\Xenon-Bot-JavaScript-Edition-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
(node:11772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How do I fix this error?

**Comment by REVENGE977** [comment]
I think this is because you installed discord.js 12
go back to discord.js 11

npm i discord.js@11
