### ISSUE TITLE
Help me PLZ

### ISSUE THREAD

**Issue by ghost** [Bowlingtoolkit/Xenon-Bot-JavaScript-Edition#6]
Debugger listening on ws://127.0.0.1:20674/11835bce-d422-4c17-b086-ed1334a4657b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Found 7 files to load!

CommandHandler.js:25
Error: ENOENT: no such file or directory, open './Data/backups.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.<anonymous> (c:\Users\Ezori\Documents\Bot2\Commands\backup.js:5:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at CommandHandler._loadFrom (c:\Users\Ezori\Documents\Bot2\node_modules\djs-commands\CommandHandler.js:28:26)

**Comment by Dany-LF** [comment]
Re download, all work.

**Comment by REVENGE977** [comment]
create backups.json file inside Data directory and type inside it {}
